# Generated by Django 2.0 on 2017-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
