# Generated by Django 2.0 on 2017-12-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicemodel', '0002_auto_20171218_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
