# Generated by Django 2.0 on 2017-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicemodel', '0003_auto_20171218_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
